language: cpp
dist: xenial
compiler: gcc

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./scripts/install_oclint
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install sloccount
  # proselint
  - sudo pip install proselint
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

script: 
  # Build and run the tests
  - qmake
  - make --silent debug
  - ./cicone
  # helgrind
  - valgrind --tool=helgrind --log-file=helgrind.log -v ./cicone
  - cat helgrind.log
  # memcheck
  - valgrind --leak-check=full -v --show-reachable=yes --log-file=memcheck.log ./cicone
  - cat memcheck.log
  # Build and run and profile normal program
  - qmake
  - make --silent release
  - time ./cicone
  - gprof cicone > gprof.log
  - head gprof.log -n 1000
  # Get code coverage
  - ./scripts/get_code_cov
  - codecov
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./scripts/do_oclint
  # proselint
  - proselint README.md
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links
  # Get my folder
  - my_github=${PWD##*/}  
  # SLOCcount
  #   remove OCLint and .git, otherwise it will be counted as well
  - rm -rf oclint-0.10.3 oclint-0.10.3-x86_64-linux-3.13.0-74-generic.tar.gz oclint.log
  - rm -rf .git
  - rm -rf debug
  - rm -rf release
  - cd ..; sloccount --overhead 1 --personcost 22614 $my_github; cd $my_github

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
